/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: morphy.vision (https://sketchfab.com/morphy.vision)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/blue-flower-animated-c20b1f12833148e09f7f49c3dd444906
Title: Blue Flower Animated
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Flower(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/flower/scene-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]} scale={20}>
          <group name="root">
            <group name="GLTF_SceneRootNode" rotation={[Math.PI / 2, 0, 0]}>
              <group name="Anim_blye_90">
                <group name="GLTF_created_0">
                  <group name="BloomBlye001_L_0" scale={0.01} />
                  <group name="BloomBlye002_L_1" scale={0.01} />
                  <group name="BloomBlye003_L_2" scale={0.01} />
                  <group name="BloomBlye004_L_3" scale={0.01} />
                  <group name="BloomBlye005_L_4" scale={0.01} />
                  <group name="BloomBlye006_L_5" scale={0.01} />
                  <group name="BloomBlye_L_6" scale={0.01} />
                  <group name="BloomSTBlye001_L_7" scale={0.01} />
                  <group name="BloomSTBlye002_L_8" scale={0.01} />
                  <group name="BloomSTBlye003_L_9" scale={0.01} />
                  <group name="BloomSTBlye004_L_10" scale={0.01} />
                  <group name="BloomSTBlye005_L_11" scale={0.01} />
                  <group name="BloomSTBlye006_L_12" scale={0.01} />
                  <group name="BloomSTBlye_L_13" scale={0.01} />
                  <group name="Petal001-_76" scale={0.01} />
                  <group name="Petal002-_77" scale={0.01} />
                  <group name="Petal003Blye_L_78" scale={0.01} />
                  <group name="Petal004Blye_L_79" scale={0.01} />
                  <group name="PetalBlye_L_80" scale={0.01} />
                  <group name="stemBlye02_L_88" scale={0.01} />
                  <group name="stemBlye_L_89" scale={0.01} />
                  <primitive object={nodes.GLTF_created_0_rootJoint} />
                  <skinnedMesh name="Object_21" geometry={nodes.Object_21.geometry} material={materials.Iris_and_blye} skeleton={nodes.Object_21.skeleton} />
                  <skinnedMesh name="Object_23" geometry={nodes.Object_23.geometry} material={materials.Iris_and_blye} skeleton={nodes.Object_23.skeleton} />
                  <skinnedMesh name="Object_25" geometry={nodes.Object_25.geometry} material={materials.Iris_and_blye} skeleton={nodes.Object_25.skeleton} />
                  <skinnedMesh name="Object_27" geometry={nodes.Object_27.geometry} material={materials.Iris_and_blye} skeleton={nodes.Object_27.skeleton} />
                  <skinnedMesh name="Object_29" geometry={nodes.Object_29.geometry} material={materials['Iris_and_blye.001']} skeleton={nodes.Object_29.skeleton} />
                  <skinnedMesh name="Object_31" geometry={nodes.Object_31.geometry} material={materials.stem} skeleton={nodes.Object_31.skeleton} />
                  <skinnedMesh name="Object_33" geometry={nodes.Object_33.geometry} material={materials.stem} skeleton={nodes.Object_33.skeleton} />
                  <skinnedMesh name="Object_35" geometry={nodes.Object_35.geometry} material={materials.Iris_and_blye} skeleton={nodes.Object_35.skeleton} />
                  <skinnedMesh name="Object_37" geometry={nodes.Object_37.geometry} material={materials.Iris_and_blye} skeleton={nodes.Object_37.skeleton} />
                  <skinnedMesh name="Object_39" geometry={nodes.Object_39.geometry} material={materials.Iris_and_blye} skeleton={nodes.Object_39.skeleton} />
                  <skinnedMesh name="Object_41" geometry={nodes.Object_41.geometry} material={materials.Iris_and_blye} skeleton={nodes.Object_41.skeleton} />
                  <skinnedMesh name="Object_43" geometry={nodes.Object_43.geometry} material={materials.Iris_and_blye} skeleton={nodes.Object_43.skeleton} />
                  <skinnedMesh name="Object_45" geometry={nodes.Object_45.geometry} material={materials.Iris_and_blye} skeleton={nodes.Object_45.skeleton} />
                  <skinnedMesh name="Object_47" geometry={nodes.Object_47.geometry} material={materials.Iris_and_blye} skeleton={nodes.Object_47.skeleton} />
                  <skinnedMesh name="Object_54" geometry={nodes.Object_54.geometry} material={materials.Iris_and_blye} skeleton={nodes.Object_54.skeleton} />
                  <skinnedMesh name="Object_56" geometry={nodes.Object_56.geometry} material={materials.Iris_and_blye} skeleton={nodes.Object_56.skeleton} />
                  <skinnedMesh name="Object_58" geometry={nodes.Object_58.geometry} material={materials.Iris_and_blye} skeleton={nodes.Object_58.skeleton} />
                  <skinnedMesh name="Object_60" geometry={nodes.Object_60.geometry} material={materials.Iris_and_blye} skeleton={nodes.Object_60.skeleton} />
                  <skinnedMesh name="Object_62" geometry={nodes.Object_62.geometry} material={materials.Iris_and_blye} skeleton={nodes.Object_62.skeleton} />
                  <skinnedMesh name="Object_64" geometry={nodes.Object_64.geometry} material={materials.Iris_and_blye} skeleton={nodes.Object_64.skeleton} />
                  <skinnedMesh name="Object_66" geometry={nodes.Object_66.geometry} material={materials.Iris_and_blye} skeleton={nodes.Object_66.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/flower/scene-transformed.glb')
