/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: atos0528 (https://sketchfab.com/atos0528)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/end-flower9-4be8021f30974c8e8a223b131a5f01f9
Title: End Flower9
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function FlowerBloom(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/flower_bloom/scene-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" position={[0.04, 0.09, -0.01]} rotation={[-1.44, 0.31, -0.03]} scale={2.85}>
          <group name="Root">
            <group name="Armature" rotation={[-Math.PI / 2, Math.PI / 6, 0]}>
              <group name="Armature_rootJoint">
                <group name="Bone020_Armature" position={[0, 0.03, 0]} rotation={[0, Math.PI / 2, 0]}>
                  <group name="Bone_Armature" position={[0, -0.03, 0]} rotation={[2.95, 0.18, -1.07]}>
                    <group name="C_2" rotation={[-0.08, -1.36, -0.09]} scale={0.92}>
                      <mesh name="C_2_0" geometry={nodes.C_2_0.geometry} material={materials['Scene_-_Root']} />
                    </group>
                  </group>
                  <group name="Bone001_Armature" position={[0.01, -0.03, 0.01]} rotation={[1.71, -0.09, -0.55]}>
                    <group name="B_2" position={[0, -0.01, 0]} rotation={[0.18, 0.01, 0.03]}>
                      <mesh name="B_2_0" geometry={nodes.B_2_0.geometry} material={materials['Scene_-_Root']} />
                    </group>
                  </group>
                  <group name="Bone002_Armature" position={[0.01, -0.03, 0.01]} rotation={[1.43, -0.1, -2.5]}>
                    <group name="B_1" position={[0.01, 0, 0]} rotation={[0.18, 0.02, 0.05]}>
                      <mesh name="B_1_0" geometry={nodes.B_1_0.geometry} material={materials['Scene_-_Root']} />
                    </group>
                  </group>
                  <group name="Bone003_Armature" position={[0, -0.03, 0]} rotation={[1.64, 0.04, 0.53]}>
                    <group name="A_1" rotation={[0.09, 0, -0.01]}>
                      <mesh name="A_1_0" geometry={nodes.A_1_0.geometry} material={materials['Scene_-_Root']} />
                    </group>
                  </group>
                  <group name="Bone004_Armature" position={[0.01, -0.03, 0.01]} rotation={[1.57, -0.08, -1.59]}>
                    <group name="A_2" position={[0.01, -0.01, 0]} rotation={[0.09, 0, 0.02]}>
                      <mesh name="A_2_0" geometry={nodes.A_2_0.geometry} material={materials['Scene_-_Root']} />
                    </group>
                  </group>
                  <group name="Bone005_Armature" position={[0.01, -0.03, 0.01]} rotation={[1.49, 0.03, 2.79]}>
                    <group name="A_3" position={[0, 0.01, 0]} rotation={[0.09, 0, 0.01]}>
                      <mesh name="A_3_0" geometry={nodes.A_3_0.geometry} material={materials['Scene_-_Root']} />
                    </group>
                  </group>
                  <group name="Bone006_Armature" position={[0, -0.03, 0]} rotation={[1.58, 0.17, 1.54]}>
                    <group name="B_3" rotation={[0.18, 0.01, 0.03]}>
                      <mesh name="B_3_0" geometry={nodes.B_3_0.geometry} material={materials['Scene_-_Root']} />
                    </group>
                  </group>
                  <group name="Bone007_Armature" position={[0, -0.03, 0]} rotation={[1.78, 0.38, 0.76]}>
                    <group name="C_1" rotation={[0.02, -0.12, 0.02]} scale={0.92}>
                      <mesh name="C_1_0" geometry={nodes.C_1_0.geometry} material={materials['Scene_-_Root']} />
                    </group>
                  </group>
                  <group name="Bone009_Armature" position={[0, -0.03, 0]} rotation={[-1.9, -0.68, 0.15]}>
                    <group name="C_3" rotation={[3.13, -0.65, -3.11]} scale={0.92}>
                      <mesh name="C_3_0" geometry={nodes.C_3_0.geometry} material={materials['Scene_-_Root']} />
                    </group>
                  </group>
                  <group name="Bone010_Armature" position={[0, -0.03, 0]} rotation={[-2.19, 0.26, -0.9]}>
                    <group name="D_2" rotation={[-3.11, -0.36, 3.12]} scale={0.79}>
                      <mesh name="D_2_0" geometry={nodes.D_2_0.geometry} material={materials['Scene_-_Root']} />
                    </group>
                  </group>
                  <group name="Bone011_Armature" position={[0, -0.03, 0]} rotation={[2.44, 0.12, -0.07]}>
                    <group name="F_1" rotation={[0.01, -0.12, 0.08]} scale={0.57}>
                      <mesh name="F_1_0" geometry={nodes.F_1_0.geometry} material={materials['Scene_-_Root']} />
                    </group>
                  </group>
                  <group name="Bone012_Armature" position={[0, -0.03, 0]} rotation={[2.62, 1.39, -0.5]}>
                    <group name="D_3" rotation={[-0.21, -1.41, -0.12]} scale={0.79}>
                      <mesh name="D_3_0" geometry={nodes.D_3_0.geometry} material={materials['Scene_-_Root']} />
                    </group>
                  </group>
                  <group name="Bone013_Armature" position={[0, -0.03, 0]} rotation={[1.38, 0.52, 2.1]}>
                    <group name="D_1" rotation={[-0.02, 0.11, 0.02]} scale={0.79}>
                      <mesh name="D_1_0" geometry={nodes.D_1_0.geometry} material={materials['Scene_-_Root']} />
                    </group>
                  </group>
                  <group name="Bone014_Armature" position={[0, -0.03, 0]} rotation={[1.34, 0.8, 1.28]}>
                    <group name="E_3" rotation={[0.05, -0.52, 0.07]} scale={0.79}>
                      <mesh name="E_3_0" geometry={nodes.E_3_0.geometry} material={materials['Scene_-_Root']} />
                    </group>
                  </group>
                  <group name="Bone015_Armature" position={[0, -0.03, 0]} rotation={[-2.52, 0.75, -1.3]}>
                    <group name="E_1" rotation={[3.04, -1.02, 3.07]} scale={0.79}>
                      <mesh name="E_1_0" geometry={nodes.E_1_0.geometry} material={materials['Scene_-_Root']} />
                    </group>
                  </group>
                  <group name="Bone016_Armature" position={[0, -0.03, 0]} rotation={[-2.24, 0.59, 0.03]}>
                    <group name="E_2" rotation={[3.09, 0.59, -3.09]} scale={0.79}>
                      <mesh name="E_2_0" geometry={nodes.E_2_0.geometry} material={materials['Scene_-_Root']} />
                    </group>
                  </group>
                  <group name="Bone017_Armature" position={[0, -0.03, 0]} rotation={[-2.54, 0.34, -0.67]}>
                    <group name="F_3" rotation={[-3.14, -0.53, 3.09]} scale={0.57}>
                      <mesh name="F_3_0" geometry={nodes.F_3_0.geometry} material={materials['Scene_-_Root']} />
                    </group>
                  </group>
                  <group name="Bone018_Armature" position={[0, -0.03, 0]} rotation={[-3, 0.36, 0.6]}>
                    <group name="F_2" rotation={[-2.96, 1.36, 2.96]} scale={0.57}>
                      <mesh name="F_2_0" geometry={nodes.F_2_0.geometry} material={materials['Scene_-_Root']} />
                    </group>
                  </group>
                  <group name="Bone019_Armature" position={[0, -0.03, 0]} rotation={[3.14, 0.65, 0]}>
                    <group name="G_2" rotation={[-0.63, -0.55, -0.36]} scale={[0.21, 0.32, 0.32]}>
                      <mesh name="G_2_0" geometry={nodes.G_2_0.geometry} material={materials['Scene_-_Root']} />
                    </group>
                  </group>
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/flower_bloom/scene-transformed.gl')
