/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scene.gltf --transform
Author: Eryn_Noel (https://sketchfab.com/Eryn_Noel)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/assignment4-flowersfbx-94645483db6e44819436e3a92a202efc
Title: Assignment4_FlowersFBX
*/

import React, { useRef } from 'react'
import { useGLTF, useAnimations } from '@react-three/drei'

export function Lavender(props) {
  const group = useRef()
  const { nodes, materials, animations } = useGLTF('./models/lavender/scene-transformed.glb')
  const { actions } = useAnimations(animations, group)
  return (
    <group ref={group} {...props} dispose={null}>
      <group name="Sketchfab_Scene">
        <group name="Sketchfab_model" rotation={[-Math.PI / 2, 0, 0]}>
          <group name="fd08bc535fbb4a65a9a9b876d612e9effbx" rotation={[Math.PI / 2, 0, 0]}>
            <group name="Object_2">
              <group name="RootNode">
                <group name="Object_4">
                  <primitive object={nodes._rootJoint} />
                  <group name="polySurface1" position={[0.61, -1.3, 0.41]} rotation={[-2.79, 1.15, 3.11]} scale={0.68}>
                    <mesh name="polySurface1_lambert1_0" geometry={nodes.polySurface1_lambert1_0.geometry} material={materials.lambert1} />
                  </group>
                  <group name="group47_pasted__group36_pasted__pasted__group_pasted__pasted__pasted__pCube1" position={[0.48, 0.32, -0.12]} rotation={[0, -0.62, 0]} scale={[0.95, 0.41, 0.95]}>
                    <mesh name="group47_pasted__group36_pasted__pasted__group_pasted__pasted__pasted__pCube1_lambert1_0" geometry={nodes.group47_pasted__group36_pasted__pasted__group_pasted__pasted__pasted__pCube1_lambert1_0.geometry} material={materials.lambert1} />
                  </group>
                  <group name="group70">
                    <group name="pasted__polySurface1" position={[1.16, -2.47, 1.64]} rotation={[-0.18, -0.7, 0.09]} scale={0.82}>
                      <mesh name="pasted__polySurface1_lambert1_0" geometry={nodes.pasted__polySurface1_lambert1_0.geometry} material={materials.lambert1} />
                    </group>
                  </group>
                  <skinnedMesh name="Object_7" geometry={nodes.Object_7.geometry} material={materials.lambert1} skeleton={nodes.Object_7.skeleton} />
                  <skinnedMesh name="Object_9" geometry={nodes.Object_9.geometry} material={materials.lambert1} skeleton={nodes.Object_9.skeleton} />
                </group>
              </group>
            </group>
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('./models/lavender/scene-transformed.glb')
